#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

commitMessage="$(cat $1)"

if [[ "$commitMessage" =~ ([A-Z][A-Z0-9]+-[0-9]+) ]]; then
  echo ""
  echo "Great work! 🥂"
  echo ""
else
  echo ""
  echo "Wrong commit message! 🚨"
  echo "The commit message must start with this format:"
  echo "eg. EX-01 ..."
  echo ""
  echo "Your commit message was:"
  echo $commitMessage
  echo ""
  echo "For more information, check script in .husky/commit-msg"
  echo ""
  echo ""
  exit 1
fi
